version: "3.9"

services:
  backend:
    container_name: term-alarms-server
    build:
      context: ../../.
      dockerfile: cmd/server/Dockerfile
    ports:
      - 3000:8080
    env_file:
      - .env
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: "500MB"
