version: "3.9"

services:
  backend:
    container_name: term-alarms-server
    build:
      context: ../../.
      dockerfile: cmd/server/Dockerfile
    ports:
      - 3000:8080
    env_file:
      - .env
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: "500MB"
  mongo:
    image: mongo
    container_name: term-alarms-mongo
    restart: always
    ports:
      - 27017:27017
    env_file:
      - .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASS}
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: "1000MB"
  mongo-express:
    image: mongo-express
    container_name: term-alarms-mongo-web
    restart: always
    depends_on:
      - mongo
    ports:
      - 8081:8081
    env_file:
      - .env
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_PASS}
      ME_CONFIG_MONGODB_URL: mongodb://${MONGO_USER}:${MONGO_PASS}@mongo:${MONGO_PORT}
      ME_CONFIG_BASICAUTH: false
    deploy:
      resources:
        limits:
          cpus: "0.4"
          memory: "250MB"
  mailer:
    image: axllent/mailpit:v1.19
    container_name: term-alarms-mailer
    restart: always
    ports:
      - 8025:8025
      - 1025:1025
    environment:
      MP_SMTP_REQUIRE_TLS: false
      MP_SMTP_AUTH_ACCEPT_ANY: true
      MP_SMTP_REQUIRE_STARTTLS: false
      MP_SMTP_AUTH_ALLOW_INSECURE: true
    deploy:
      resources:
        limits:
          cpus: "0.4"
          memory: "250MB"
