basePath: /
info:
  contact:
    email: richhh7g@protonmail.com
    name: Richhh7g
    url: https://github.com/richhh7g
  description: API do Term Alarms para monitorar concorrentes que usam termos de marca
    em resultados patrocinados do Google.
  license:
    name: MIT
    url: https://github.com/richhh7g/term-alarms/blob/main/LICENSE
  title: Term Alarms
  version: 1.0.0
paths: {}
swagger: "2.0"
